/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package corbivisualizer;

import java.io.*;
import java.nio.charset.Charset;

import javafx.application.Application;
import javafx.scene.*;
import javafx.stage.Stage;
import javafx.scene.shape.*;
import corbivisualizer.communication.*;
import corbivisualizer.ui.*;

public class App extends Application
{

    private static Rectangle rect = new Rectangle();

    @Override
    public void start(Stage stage)
    {
        Group root = new Group();
        // TODO この辺のプロパティ、どっかでまとめて定義しておいてくだちい
        Scene scene = new Scene(root, 800, 600);
        //DynamicBar dynamicBar = new DynamicBar(400, 300, 90, 100, 10);
        DynamicBar dynamicBar = new DynamicBar();
        dynamicBar.setX(0).setY(10).setAngle(270).setWidth(10);
        root.getChildren().add(dynamicBar);
        CorBiCoreReader corbiReader = new CorBiCoreReader(length -> dynamicBar.updateLength(length)).setDummy();
        new Thread(corbiReader::read).start();
        stage.setOnCloseRequest(event ->
        {
            corbiReader.destroy();
            System.exit(0);
        });
        stage.setScene(scene);
        stage.show();
    }

    public static void main(String[] args)
    {
        launch();
    }

}
